# Average over items for each user

Idea: impute missing values by taking average rating over items for each user

In [1]:
import numpy as np

from helpers import load_data, write_submission_file

## Load training data

In [2]:
X = load_data()
print(X[0:10,0:10])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 5.]
 [0. 0. 0. 3. 0. 5. 0. 4. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 5. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0. 5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 5. 0. 0. 0. 3.]
 [0. 0. 0. 1. 0. 5. 0. 5. 0. 0.]]


## Impute missing entries (average rating per user)

In [3]:
y = X.sum(axis=1)
rating_counts = np.count_nonzero(X, axis =1)
average_per_user = y/rating_counts
X_pred = np.copy(X)
for row in range(X.shape[0]):
    no_rating = (X[row, :] == 0)
    X_pred[row, no_rating] = average_per_user[row]
print(X_pred[0:10, 0:10])


[[4.04347826 4.04347826 4.04347826 4.04347826 4.04347826 4.04347826
  4.04347826 4.04347826 4.04347826 5.        ]
 [3.77181208 3.77181208 3.77181208 3.         3.77181208 5.
  3.77181208 4.         3.77181208 3.77181208]
 [3.52325581 3.52325581 3.52325581 2.         3.52325581 3.52325581
  3.52325581 3.52325581 3.52325581 3.52325581]
 [3.8        3.8        3.8        3.8        3.8        3.8
  3.8        3.8        3.8        3.8       ]
 [3.98507463 2.         3.98507463 3.98507463 3.98507463 5.
  3.98507463 3.         3.98507463 3.98507463]
 [4.36686391 4.36686391 4.36686391 4.36686391 4.36686391 5.
  4.36686391 4.36686391 4.36686391 4.36686391]
 [4.12903226 4.12903226 4.12903226 4.12903226 4.12903226 4.12903226
  4.12903226 4.12903226 4.12903226 4.12903226]
 [4.11538462 4.11538462 4.11538462 4.11538462 4.11538462 4.11538462
  4.11538462 4.11538462 4.11538462 4.11538462]
 [3.97191011 3.97191011 3.97191011 3.97191011 3.97191011 5.
  3.97191011 3.97191011 3.97191011 3.        ]
 [3.

## Output submission file 

In [4]:
output = write_submission_file(X_pred, "submission_average_over_items_0.csv")
print(output[0:100])

Id,Prediction
r37_c1,3.757732
r73_c1,3.540000
r156_c1,4.230216
r160_c1,3.692308
r248_c1,3.928144
r25
