# Average over users for each item

Idea: impute missing values by taking average rating over users for each item

In [2]:
import numpy as np

from helpers import load_data, write_submission_file

## Load training data

In [3]:
X = load_data()
print(X[0:10,0:10])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 5.]
 [0. 0. 0. 3. 0. 5. 0. 4. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 5. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0. 5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 5. 0. 0. 0. 3.]
 [0. 0. 0. 1. 0. 5. 0. 5. 0. 0.]]


## Impute missing entries (average rating per item)

In [4]:
y = X.sum(axis=0)
rating_counts = np.count_nonzero(X, axis=0)
average_per_item = y/rating_counts
X_pred = np.copy(X)
for column in range(X.shape[1]):
    no_rating = (X[:, column] == 0)
    X_pred[no_rating, column] = average_per_item[column]
print(X_pred[0:10, 0:10])

[[3.37941176 3.50094162 3.48358586 3.93647282 3.55913113 4.68276973
  3.44661922 3.87749706 2.90196078 5.        ]
 [3.37941176 3.50094162 3.48358586 3.         3.55913113 5.
  3.44661922 4.         2.90196078 3.6460717 ]
 [3.37941176 3.50094162 3.48358586 2.         3.55913113 4.68276973
  3.44661922 3.87749706 2.90196078 3.6460717 ]
 [3.37941176 3.50094162 3.48358586 3.93647282 3.55913113 4.68276973
  3.44661922 3.87749706 2.90196078 3.6460717 ]
 [3.37941176 2.         3.48358586 3.93647282 3.55913113 5.
  3.44661922 3.         2.90196078 3.6460717 ]
 [3.37941176 3.50094162 3.48358586 3.93647282 3.55913113 5.
  3.44661922 3.87749706 2.90196078 3.6460717 ]
 [3.37941176 3.50094162 3.48358586 3.93647282 3.55913113 4.68276973
  3.44661922 3.87749706 2.90196078 3.6460717 ]
 [3.37941176 3.50094162 3.48358586 3.93647282 3.55913113 4.68276973
  3.44661922 3.87749706 2.90196078 3.6460717 ]
 [3.37941176 3.50094162 3.48358586 3.93647282 3.55913113 5.
  3.44661922 3.87749706 2.90196078 3.       

## Output submission file 

In [5]:
output = write_submission_file(X_pred, 'submission_average_over_users_0.csv')
print(output[0:100])

NameError: name 'os' is not defined